from django.contrib import admin

from .models import *

admin.site.register(Property)
admin.site.register(ImagesProperty)
admin.site.register(PropertyLocation)
admin.site.register(GuestControls)
admin.site.register(InternetOptions)
admin.site.register(BedroomsBathrooms)
admin.site.register(Bedrooms)
admin.site.register(LivingRooms)
admin.site.register(Bathroom)
admin.site.register(Availability)
admin.site.register(Pricing)
admin.site.register(Deposits)
admin.site.register(FeeAccounts)
admin.site.register(DebitAccount)
admin.site.register(CreditAccount)
admin.site.register(RefundPolicies)
admin.site.register(Units)
admin.site.register(ReservationNew)
admin.site.register(ReservationInformation)
admin.site.register(LineItemFee)
admin.site.register(LineItemTax)
admin.site.register(PropertyListing)
admin.site.register(UnitListing)
admin.site.register(CustomerInformation)
admin.site.register(Charge)
admin.site.register(PaymentMethod)
admin.site.register(Note)
admin.site.register(WorkOrder)
admin.site.register(OwnerSplit)
admin.site.register(Portfolio)

