
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('date_format', models.CharField(blank=True, max_length=255, null=True)),
                ('default', models.BooleanField(blank=True, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verify_image', models.CharField(blank=True, max_length=255, null=True)),
                ('verify_image_description', models.TextField(blank=True, null=True)),
                ('verify_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('rate_inflator', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cms_version', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=100, null=True)),
                ('subdomain', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms_agreement', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green'), ('purple', 'Purple')], default='green', max_length=10)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('is_organization_created', models.BooleanField(default=False, null=True)),
                ('is_payment_done', models.BooleanField(default=False, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=257, null=True)),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.companytype')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.currency')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.language')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.location')),
                ('organization_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.organizationtype')),
                ('payment_processor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.paymentprocessor')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.subscriptionplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandFooters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scripts', models.TextField(blank=True, null=True)),
                ('sections', models.JSONField(blank=True, null=True)),
                ('credit_cards', models.JSONField(blank=True, null=True)),
                ('intercom_id', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_html', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_tags', models.JSONField(blank=True, null=True)),
                ('custom_html', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandHomePages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.IntegerField(null=True)),
                ('payload', models.JSONField(null=True)),
                ('options', models.TextField(max_length=256, null=True)),
                ('meta_title', models.CharField(max_length=257, null=True)),
                ('meta_description', models.CharField(max_length=258, null=True)),
                ('cms_display_name', models.CharField(max_length=259)),
                ('title', models.CharField(max_length=260)),
                ('description', models.CharField(max_length=261)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.IntegerField(blank=True, null=True)),
                ('colors', models.JSONField(blank=True, null=True)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('css_override', models.TextField(blank=True, null=True)),
                ('fonts', models.JSONField(blank=True, null=True)),
                ('social', models.JSONField(blank=True, null=True)),
                ('google_analytics', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_image', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_image_processing', models.BooleanField(blank=True, null=True)),
                ('favicon_image', models.CharField(blank=True, max_length=255, null=True)),
                ('favicon_image_processing', models.BooleanField(blank=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(null=True)),
                ('robots', models.CharField(max_length=2048, null=True)),
                ('robots_name', models.CharField(max_length=255, null=True)),
                ('custom_hero_html', models.TextField(null=True)),
                ('scripts_override', models.TextField(null=True)),
                ('bootstrap4', models.BooleanField(null=True)),
                ('body_class', models.CharField(max_length=255, null=True)),
                ('google_tag_manager', models.CharField(max_length=255, null=True)),
                ('facebook_pixel', models.CharField(max_length=255, null=True)),
                ('hubspot_tracking', models.CharField(max_length=255, null=True)),
                ('google_events', models.BooleanField(null=True)),
                ('google_verification', models.CharField(max_length=255, null=True)),
                ('legacy', models.BooleanField(null=True)),
                ('logo_white_image', models.CharField(max_length=255, null=True)),
                ('logo_white_image_processing', models.BooleanField()),
                ('book_now', models.JSONField()),
                ('send_message', models.JSONField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('slug', models.CharField(max_length=255, null=True)),
                ('payload', models.JSONField(null=True)),
                ('featured', models.BooleanField(null=True)),
                ('published', models.BooleanField(null=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('contact_form', models.BooleanField(null=True)),
                ('css_override', models.TextField(null=True)),
                ('scripts_override', models.TextField(null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.CharField(max_length=255, null=True)),
                ('cms_display_name', models.CharField(max_length=255, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities_data', models.JSONField(blank=True, null=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceFeaturedListings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('listings_data', models.JSONField(blank=True, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceGridContentBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('column_data', models.JSONField(blank=True, null=True)),
                ('number_of_columns', models.IntegerField(blank=True, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceHeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('headline_text', models.CharField(max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brandpagesliceheros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('bg_image', models.CharField(max_length=255, null=True)),
                ('bg_image_gallery', models.JSONField(null=True)),
                ('bg_video', models.CharField(max_length=255, null=True)),
                ('bg_type', models.IntegerField(null=True)),
                ('headline', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceHomepageHeros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('bg_image', models.CharField(max_length=255, null=True)),
                ('bg_image_gallery', models.JSONField(null=True)),
                ('bg_video', models.CharField(max_length=255, null=True)),
                ('bg_type', models.IntegerField(null=True)),
                ('headline', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('layout_type', models.IntegerField(null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceLocalActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('local_activities_data', models.JSONField(blank=True, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceMediaContentBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('bg_image', models.CharField(max_length=255, null=True)),
                ('bg_image_gallery', models.JSONField(null=True)),
                ('bg_video', models.CharField(max_length=255, null=True)),
                ('bg_type', models.IntegerField(null=True)),
                ('headline', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSlicePhotoGalleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('photo_gallery', models.JSONField(null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSlicePullQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('quote_text', models.CharField(max_length=255, null=True)),
                ('quote_author', models.CharField(max_length=255, null=True)),
                ('quote_author_image', models.CharField(max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(blank=True, null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('review_data', models.JSONField(blank=True, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSlices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('slice_key', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceSingleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('width', models.IntegerField(null=True)),
                ('justify', models.IntegerField(null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandPageSliceVideoEmbeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_sort', models.IntegerField(null=True)),
                ('custom_name', models.CharField(max_length=255, null=True)),
                ('video_url', models.CharField(max_length=255, null=True)),
                ('video_source', models.IntegerField(null=True)),
                ('width', models.CharField(max_length=255, null=True)),
                ('justify', models.IntegerField(null=True)),
                ('brand_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brandpages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandsEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.BigIntegerField()),
                ('all_id', models.BigIntegerField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='organization.organization')),
                ('tenant_domains', models.TextField(blank=True, null=True)),
                ('pmc_messages_only', models.BooleanField(blank=True, default=True, null=True)),
                ('verification_message_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('verification_reminder_message_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('inquiry_received_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('after_booking_confirmed_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('check_in_instructions_verified_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('check_in_instructions_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('welcome_to_stay_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('how_was_stay_enabled', models.BooleanField(blank=True, default=False, null=True)),
                ('pointcentral_seamless_token', models.CharField(blank=True, max_length=251, null=True)),
                ('pointcentral_session_token', models.CharField(blank=True, max_length=252, null=True)),
                ('global_date_format', models.IntegerField(blank=True, default=1, null=True)),
                ('should_split_bookings', models.BooleanField(blank=True, default=False, null=True)),
                ('add_on_images', models.BooleanField(blank=True, default=False, null=True)),
                ('kaba_access_token', models.CharField(blank=True, max_length=253, null=True)),
                ('kaba_site_name', models.CharField(blank=True, max_length=254, null=True)),
                ('csa_insurance_fee_rate', models.CharField(blank=True, max_length=250, null=True)),
                ('csa_insurance_key', models.CharField(blank=True, max_length=257, null=True)),
                ('keydata_token', models.TextField(blank=True, null=True)),
                ('keydata_token_exp', models.CharField(blank=True, max_length=259, null=True)),
                ('is_keydata_registered', models.BooleanField(blank=True, null=True)),
                ('keydata_pmid', models.CharField(blank=True, max_length=260, null=True)),
                ('keydata_embed_code', models.TextField(blank=True, null=True)),
                ('locked', models.BooleanField(blank=True, default=True, null=True)),
                ('payment_processor', models.IntegerField(blank=True, default=1, null=True)),
                ('rvshare_import_batch_id', models.CharField(blank=True, max_length=262, null=True)),
                ('feature_tier', models.TextField()),
                ('annual_maintenance_fee_added_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
