# Generated by Django 5.1.6 on 2025-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandinfos',
            name='logo_white_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
