# Generated by Django 5.1.6 on 2025-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_workorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
