# Generated by Django 5.1.6 on 2025-05-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_workreport_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workreport',
            name='work_order',
            field=models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, to='property.workorder'),
        ),
    ]
