# Generated by Django 5.1.6 on 2025-05-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
        ('property', '0005_alter_workreport_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_emails', models.JSONField(blank=True, default=list)),
                ('terms_and_conditions', models.TextField(blank=True, default='')),
                ('e_sig_required', models.BooleanField(default=False)),
                ('photo_id_required', models.BooleanField(default=False)),
                ('address_required', models.BooleanField(default=False)),
                ('age_required', models.BooleanField(default=False)),
                ('required_age', models.IntegerField(default=18)),
                ('photo_id_description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('contract_body', models.TextField(blank=True, default='')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='external_contracts', to='organization.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='units',
            name='external_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.externalcontract'),
        ),
        migrations.CreateModel(
            name='LynnbrookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('funding_type', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('encrypted_checkbook_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_checkbook_api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('checkbook_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('encrypted_checkbook_api_key_iv', models.TextField(blank=True, null=True)),
                ('encrypted_checkbook_api_secret_iv', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lynnbrook_accounts', to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='lynnbrook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.lynnbrookaccount'),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('bedroom_count', models.FloatField(blank=True, null=True)),
                ('bathroom_count', models.FloatField(blank=True, null=True)),
                ('guest_count', models.IntegerField(blank=True, null=True)),
                ('bed_config', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('default_availability_changeover', models.CharField(blank=True, max_length=255, null=True)),
                ('default_stay_max', models.IntegerField(blank=True, null=True)),
                ('default_stay_min', models.IntegerField(blank=True, null=True)),
                ('default_time_check_in', models.CharField(blank=True, max_length=255, null=True)),
                ('default_time_check_out', models.CharField(blank=True, max_length=255, null=True)),
                ('default_prior_notify_min', models.IntegerField(blank=True, null=True)),
                ('default_nightly_weekday', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_nightly_weekend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_full_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_full_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('organization_id', models.IntegerField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_types', to='property.property')),
            ],
        ),
        migrations.AddField(
            model_name='units',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='property.roomtype'),
        ),
        migrations.AddIndex(
            model_name='units',
            index=models.Index(fields=['external_contract'], name='property_un_externa_211ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='units',
            index=models.Index(fields=['room_type'], name='property_un_room_ty_c4051f_idx'),
        ),
    ]
